try
    x=0
catch as error
    if true
        throw error
